version: '3.8'

services:
  db:
    image: postgres:15 # Or your preferred version
    container_name: quoting_db_dev
    restart: always
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
      # Mounts the SQL scripts to be run on first-time initialization
      - ./database/init-scripts:/docker-entrypoint-initdb.d
      # Mounts the CSV data to a location accessible by the COPY command
      - ./database/data:/csv_data
    ports: # Map local port for external tools like DBeaver
      - "5433:5432" # Local 5433 maps to container 5432
    env_file:
      - .env # Load environment variables from .env

  api:
    container_name: quoting_api_dev
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/app:/app/app # Mount local code for live reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  ui:
    container_name: quoting_ui_dev
    build:
      context: ./ui
      dockerfile: Dockerfile
    volumes:
      - ./ui:/app # Mount local code for live reload
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - api
    restart: unless-stopped

  database-test:
    image: postgres:13
    container_name: fan-quoting-app-database-test
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5431:5431"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_data_dev: # Define a named volume for DB persistence
  postgres_test_data: # Define a named volume for test DB persistence