# Streamlit Configuration - PRODUCTION
# This file is for production deployment with security and minimal UI

[server]
# Don't open browser automatically
headless = true

# Disable auto-reload in production
runOnSave = false

# File watcher (poll works well in containerized environments)
fileWatcherType = "poll"

# Security
enableXsrfProtection = true
enableCORS = false

# Port
port = 8501

[browser]
# Disable usage statistics
gatherUsageStats = false

[theme]
# Custom theme colors (optional - adjust to your brand)
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[client]
# PRODUCTION: Hide detailed errors from users (security)
showErrorDetails = false

# PRODUCTION: Minimal toolbar for clean user experience
toolbarMode = "minimal"

[runner]
# Faster magic commands
magicEnabled = true

# Warning for large data
fastReruns = true
